version: '3'

services:
  strapi-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "adminadmin"
    ports:
      - "15432:5432"
    volumes:
      - ~/dev/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  strapi-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "diogo.fernandes@lb2.com.br"
      PGADMIN_DEFAULT_PASSWORD: "adminadmin"
    ports:
      - "16543:80"
    depends_on:
      - strapi-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge